"""Dataset adapter for harness-1 local RL.

Bridges the existing datagen/search_dataset.py SearchDataset class to the
format expected by verl/TRL rollout drivers.

Per KARL (arXiv:2603.05218):
  - Pass-rate filtering for SFT data (0.1 < pass_rate < 0.9)
  - ID obfuscation for multi-epoch training (Sid-1)
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Set, Tuple

from training_local.config import RLConfig, SFTConfig


@dataclass
class QueryRecord:
    """One query with its gold data, ready for rollout."""

    query_id: str
    query_text: str
    dataset_name: str
    gold_doc_ids: Set[str]
    fa_doc_ids: Set[str]
    answer: str = ""
    raw: Dict[str, Any] = None


def _hash_id(query_id: str, epoch: int) -> str:
    """Sid-1 ID obfuscation for multi-epoch training."""
    if epoch <= 0:
        return query_id
    h = hashlib.sha1(f"{query_id}|{epoch}".encode()).hexdigest()[:8]
    return f"{query_id}_{h}"


def load_queries(
    config: RLConfig,
    split: Optional[str] = None,
    epoch: int = 0,
) -> List[QueryRecord]:
    """Load all training queries across configured datasets.

    Args:
        config: RLConfig with train_datasets.
        split: override split (default: config.rl_query_split).
        epoch: epoch index, used for ID obfuscation.

    Returns:
        List of QueryRecord.
    """
    split = split or config.rl_query_split
    records: List[QueryRecord] = []

    try:
        from datagen.search_dataset import get_dataset
    except ImportError as e:
        raise ImportError(
            f"Could not import datagen.search_dataset: {e}. "
            "Ensure the harness-1 repo is on the Python path."
        )

    for ds_name in config.train_datasets:
        try:
            ds = get_dataset(ds_name)
        except Exception as e:
            raise RuntimeError(f"Failed to load dataset {ds_name}: {e}")

        if split == "train":
            ids = ds.get_train_query_ids()
        elif split == "test":
            ids = ds.get_test_query_ids()
        elif split == "rl":
            ids = ds.get_rl_query_ids()
        elif split == "sft":
            ids = ds.get_sft_query_ids()
        else:
            ids = ds.get_train_query_ids()

        if config.max_train_queries:
            ids = ids[: config.max_train_queries]

        for qid in ids:
            try:
                record = ds.get_query(qid)
            except Exception:
                continue
            if record is None:
                continue

            doc_ids = record.get("document_ids", []) if isinstance(record, dict) else []
            answer = record.get("answer", "") if isinstance(record, dict) else ""

            gold = set()
            fa = set()
            for d in doc_ids:
                if isinstance(d, str):
                    gold.add(d)
                elif isinstance(d, dict):
                    chunks = d.get("chunk_ids", [])
                    is_fa = d.get("is_final_answer", False)
                    for c in chunks:
                        gold.add(c)
                        if is_fa:
                            fa.add(c)
                else:
                    gold.add(str(d))

            records.append(
                QueryRecord(
                    query_id=_hash_id(qid, epoch),
                    query_text=record.get("query", "") if isinstance(record, dict) else str(record),
                    dataset_name=ds_name,
                    gold_doc_ids=gold,
                    fa_doc_ids=fa,
                    answer=answer,
                    raw=record if isinstance(record, dict) else {"raw": str(record)},
                )
            )

    return records


def load_sft_trajectories(config: SFTConfig) -> List[Dict[str, Any]]:
    """Load SFT trajectories generated by generate_sft_data.py.

    KARL pattern: filter by pass-rate if available.
    """
    import os
    import json

    data_dir = config.data_dir
    if not os.path.isdir(data_dir):
        raise FileNotFoundError(
            f"SFT data dir not found: {data_dir}. "
            "Run `python training_local/train_sft.py --generate-data` first."
        )

    trajectories: List[Dict[str, Any]] = []
    for fname in sorted(os.listdir(data_dir)):
        if not fname.endswith(".json"):
            continue
        path = os.path.join(data_dir, fname)
        try:
            with open(path) as f:
                data = json.load(f)
        except Exception:
            continue

        if isinstance(data, list):
            trajectories.extend(data)
        elif isinstance(data, dict):
            if "trajectories" in data:
                trajectories.extend(data["trajectories"])
            else:
                trajectories.append(data)

    # KARL pass-rate filtering
    filtered = []
    for t in trajectories:
        pass_rate = t.get("pass_rate", 0.5)
        if config.min_pass_rate <= pass_rate <= config.max_pass_rate:
            filtered.append(t)

    if config.max_train_trajectories:
        filtered = filtered[: config.max_train_trajectories]

    return filtered
